version: '2'
services:
  pg:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - ../../src/main/resources:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
